#pragma once
class AstNop;
class AstBlock;
class AstNode;
class AstObject;
class AstNumber;
class AstSymbol;
class AstFunCall;
class AstOperator;
class AstSeq;
class AstCast;
class AstCtList;
class AstFunDef;
class AstDataDef;
class AstIf;
class AstLoop;
class AstReturn;
class AstObjType;
class AstClassDef;
