#pragma once
class AstNop;
class AstBlock;
class AstNode;
class AstValue;
class AstNumber;
class AstSymbol;
class AstFunCall;
class AstOperator;
class AstCast;
class AstCtList;
class AstFunDef;
class AstFunDecl;
class AstDataDecl;
class AstArgDecl;
class AstDataDef;
class AstIf;
class AstLoop;
class AstReturn;
